[FEAT] 아티클 상세조회 기능 구현 #17
Indipage/SERVER pull request #18
Opened 2023-07-10 13:00 UTC by Jin409

## 📌 관련 이슈
- closed #17 

## ✨ 구현 내용
- 아티클 상세 조회 기능 구현

2023-07-10 19:04 UTC, sunseo18 approved these changes
최고얌~~ 이거도 마찬가지로 브랜치 명만 수정 되면 좋을 거 같은데 어짜피 머지하면 지울 거니까 그냥 머지하고 다음부터 feature로 해도됨!!1

2023-07-11 05:38 UTC, sunseo18 requested changes
이거 한 번만 확인 부탁합니당 <3

2023-07-11 05:38 UTC, sunseo18 commented on src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
> +
승히얌 여기 공간 id도 불러와야 될 거 같아!!
클라쪽에서 뷰 이동을 어떻게 할지는 모르겠지만 공간 정보 누르면 공간 뷰로이동하기도 하고
초대장 받았는지 여부도 공간 id가 필요해서!!

어떤 테이블의 정보가 필요한 경우에는 id도 필요한 경우가 많아서 데이터 불러올 때 그냥 항상 id 불러온다고 생각하면 좋을 거 같앙 : >

2023-07-11 10:30 UTC, Jin409 commented on src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
> +
오호랑 알겠습니다 🫡

2023-07-11 10:30 UTC, Jin409 commented on src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
> +
그러면 혹시~~ space 부분에는 다 space 를 붙였으니까 article entity 관련된 부분에는 다 article을 붙일까요?

2023-07-11 12:42 UTC, merged